### ISSUE TITLE
research the threshold percentages to be classified as a duplicated issue

### ISSUE THREAD

**Issue by thewro11** [samoonpride/frontend#10]
As the meeting from #9, we need to clarify this problem on the next meeting.

Acceptance Criteria:
- Research on what threshold percentages the AI model should classify the going-to-be-created issue as duplicated of the ongoing issues (specify the percentages for each of these following data: text, image, video, and location), and how the AI model should classify it.

**Comment by Natdadai** [comment]
Text (Thai)
[การทำ word2vec](https://bdi.or.th/big-data-101/word2vec-ii/)
[pretrain model](https://www.arts.chula.ac.th/ling/tnc/searchtnc/)
voice to text (Eng & Thai)
[model](https://huggingface.co/openai/whisper-large-v3)
location
Euclidean distance

**Comment by thewro11** [comment]
[TurnItIn](https://help.turnitin.com/feedback-studio/turnitin-website/instructor/the-similarity-report/interpreting-the-similarity-report.htm) website states threshold percentage for document plagiarizing classification as below:
> Blue: No matching text
> Green: One word to 24% matching text
> Yellow: 25-49% matching text
> Orange: 50-74% matching text
> Red: 75-100% matching text

So we may be able to use 50-100% matching texts as duplicated issue classification.

**Comment by thewro11** [comment]
Location distance is difficult to define. We decided to set the specific amount (25 meters) and then increase or decrease this value based on practical usage.
