### ISSUE TITLE
discuss on project creation

### ISSUE THREAD

**Issue by thewro11** [samoonpride/frontend#2]
In case of creating a new project, we have to discuss on how we should keep this project alive and progressing throughout the semester.

Acceptance Criteria:
- specify the scope and objective of this project
- create a business process diagram of this project
- schedule regular update meeting
- specify functions that are going to be created

**Comment by thewro11** [comment]
Our scope and objectives are defined in issue #1

**Comment by thewro11** [comment]
Regular update meeting is scheduled on every Tuesday (3-3:30p) and Saturday (7-7:30p).
Regular advisor meeting is scheduled on every Thursday (3:30-4:30p).

**Comment by thewro11** [comment]
Business Process Diagram: [cs499-cs-proj-business-process.pdf](https://github.com/samoonpride/frontend/files/13645723/cs499-cs-proj-business-process.pdf)

**Comment by thewro11** [comment]
We must also specify the functions of this project. Please comment functions you can think of below.

**Comment by Natdadai** [comment]
- ปักหมุดแผนที่ได้ ว่ารายงานที่ไหน
- สร้าง issue ได้จากข้อความและเสียง
- ดูความก้าวหน้าของ issue
- ดูประวัติ issue ที่เคยสร้าง

**Comment by thewro11** [comment]
**User (Citizen)** interacts with LINE Bot as the frontend application for reporting issues.
- create issues from prompting the bot with texts and/or voices (user can insert images/videos after prompting optionally)
- see created issues by related prompts
- see latest issues by related prompts

**User (Staff)** interacts with website as the frontend application for manipulating reported issues.
Frontend website must contain these pages:
- **Authentication Page** (Login, Register)
- **Change Password Page**
- **Manual Issue Creation**: User can manually create issues by accessing this page. User can define title, description, priority, location, assigned user.
- **Issue Overview**: User can see all issues and can move each issue to particular status. User can sort issues by different methods, including by creation time, updating time, assigned user, and priority.
- **Issue Description**: User can see the description of each issue, including comments and assigned user.
- **Issue Editing**: User can edit information of each issue or delete issue.

Remarks:
- Only staff with operator privilege can access register page. New staff can access the authenticated page after operator creates account for them with defined password. However, they can change their password after accessing the authenticated page.
- We must also provide the API backend to access data from database and data validation.
