### ISSUE TITLE
revisit business process diagram

### ISSUE THREAD

**Issue by thewro11** [samoonpride/frontend#5]
As we have created business process diagram from #1 before advisor meeting, we need to revisit the diagram because there are multiple changes to the project's scope.

Acceptance Criteria:
- A business process diagram is present.
- Diagram is reviewed by professor and is completely revisited after receiving feedback.

**Comment by Natdadai** [comment]
[Business process](https://drive.google.com/file/d/1qKL4iB5p3ZmRQr9NCsA77s38NuJzblWq/view?usp=sharing)

**Comment by Natdadai** [comment]
[Business Diagram.pdf](https://github.com/samoonpride/frontend/files/13724539/Business.Diagram.pdf)
![Business Diagram](https://github.com/samoonpride/frontend/assets/78583507/5035f2a8-092e-42cd-81c8-ef64d88f321e)
