### ISSUE TITLE
create use case diagram

### ISSUE THREAD

**Issue by thewro11** [samoonpride/frontend#6]
As we have created business process diagram, we have to create use case diagram to confirm the system's functions.

Acceptance Criteria:
- A use case diagram is present.
- Diagram is reviewed by professor and completely revisited after receiving feedback.

**Comment by Natdadai** [comment]
![Image](https://github.com/samoonpride/frontend/assets/78583507/3601cdba-a4a4-4c36-8ecf-98895a4bbf79)
